// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UEeKPCW7ooJJjBhUXWM13ApsPxc0Dg8',
    appId: '1:360463658490:web:a457a33e50b151960c8843',
    messagingSenderId: '360463658490',
    projectId: 'messages-cb626',
    authDomain: 'messages-cb626.firebaseapp.com',
    storageBucket: 'messages-cb626.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoi-uJxkai-eTX2o8wHmOGsyvv6Ng0xxI',
    appId: '1:360463658490:android:d60a9e89b33f379f0c8843',
    messagingSenderId: '360463658490',
    projectId: 'messages-cb626',
    storageBucket: 'messages-cb626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdHOTrAMXL6z7zTcY9Go0Y_R--tu4Wg4',
    appId: '1:360463658490:ios:f455489a7cc47be30c8843',
    messagingSenderId: '360463658490',
    projectId: 'messages-cb626',
    storageBucket: 'messages-cb626.appspot.com',
    iosClientId:
        '360463658490-up4tajj0e4hhsparesongvlhh7bo814o.apps.googleusercontent.com',
    iosBundleId: 'com.example.messages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdHOTrAMXL6z7zTcY9Go0Y_R--tu4Wg4',
    appId: '1:360463658490:ios:f455489a7cc47be30c8843',
    messagingSenderId: '360463658490',
    projectId: 'messages-cb626',
    storageBucket: 'messages-cb626.appspot.com',
    iosClientId:
        '360463658490-up4tajj0e4hhsparesongvlhh7bo814o.apps.googleusercontent.com',
    iosBundleId: 'com.example.messages',
  );
}
